import { test, expect, FIRST_SOURCE, SECOND_SOURCE, sourceButton } from './fixtures/notebook'

test('desktop panes keep each source memo through switching and reload', async ({ page, notebook }) => {
  const sources = page.getByRole('tabpanel', { name: 'ソース' })
  const study = page.getByRole('tabpanel', { name: '要約・質問' })
  const memoPanel = page.getByRole('tabpanel', { name: 'メモ' })
  await expect(sources).toBeVisible()
  await expect(study).toBeVisible()
  await expect(memoPanel).toBeVisible()

  const memo = memoPanel.getByRole('textbox', { name: 'ソースのメモ' })
  await memo.fill('貸出の手順を確認する')
  await expect(memoPanel.locator('#memo-save-status')).toHaveText('保存済み')
  await sourceButton(page, FIRST_SOURCE).click()
  await expect(page).toHaveURL(new RegExp(`sourceId=${notebook.firstSourceId}`))
  await expect(memo).toHaveValue('')
  await memo.fill('月曜日は休館')
  await expect(memoPanel.locator('#memo-save-status')).toHaveText('保存済み')
  await sourceButton(page, SECOND_SOURCE).click()
  await expect(page).toHaveURL(new RegExp(`sourceId=${notebook.secondSourceId}`))
  await expect(memo).toHaveValue('貸出の手順を確認する')
  await page.reload()
  await expect(memo).toHaveValue('貸出の手順を確認する')
  await sourceButton(page, FIRST_SOURCE).click()
  await expect(memo).toHaveValue('月曜日は休館')
})

test('submitting a question shows the new turn in the notebook', async ({ page, notebook }) => {
  await sourceButton(page, FIRST_SOURCE).click()
  await expect(page).toHaveURL(new RegExp(`sourceId=${notebook.firstSourceId}`))
  const study = page.getByRole('tabpanel', { name: '要約・質問' })
  const question = study.getByRole('textbox', { name: '質問' })
  await question.fill('開館時間は？')
  await study.getByRole('button', { name: '質問する' }).click()
  await expect(question).toHaveValue('')
  await expect(study.getByText('開館時間は？', { exact: true })).toBeVisible()
  await page.reload()
  await expect(study.getByText('開館時間は？', { exact: true })).toBeVisible()
})

test('mobile tabs preserve memo input and support arrow key focus', async ({ page, notebook }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`${notebook.path}?sourceId=${notebook.firstSourceId}`)
  const tabs = page.getByRole('tablist', { name: 'ノートの表示切替' })
  const sourcesTab = tabs.getByRole('tab', { name: 'ソース' })
  const studyTab = tabs.getByRole('tab', { name: '要約・質問' })
  const memoTab = tabs.getByRole('tab', { name: 'メモ' })
  await expect(studyTab).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tabpanel', { name: '要約・質問' })).toBeVisible()
  await expect(page.getByRole('tabpanel', { name: 'メモ', includeHidden: true })).toBeHidden()

  await expect.poll(() => studyTab.evaluate((element) =>
    Object.keys(element).some((key) => key.startsWith('__reactFiber$')),
  )).toBe(true)

  await studyTab.focus()
  await studyTab.press('ArrowRight')
  await expect(memoTab).toBeFocused()
  await expect(memoTab).toHaveAttribute('aria-selected', 'true')
  const memo = page.getByRole('textbox', { name: 'ソースのメモ' })
  await memo.fill('タブを切り替えても残るメモ')
  await memoTab.press('Home')
  await expect(sourcesTab).toBeFocused()
  await expect(page.getByRole('tabpanel', { name: 'ソース' })).toBeVisible()
  await sourcesTab.press('ArrowRight')
  await expect(studyTab).toBeFocused()
  await expect(page.getByRole('tabpanel', { name: '要約・質問' })).toBeVisible()
  await studyTab.press('ArrowRight')
  await expect(memo).toHaveValue('タブを切り替えても残るメモ')
  await expect(page.getByRole('tabpanel', { name: 'メモ' })).toBeVisible()
  await expect(page.locator('#memo-save-status')).toHaveText('保存済み')
  await page.reload()
  await memoTab.click()
  await expect(memo).toHaveValue('タブを切り替えても残るメモ')
})
