/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebooksIndexRouteImport } from './routes/notebooks.index'
import { Route as NotebooksNotebookIdRouteImport } from './routes/notebooks.$notebookId'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as SourcesSourceIdRouteImport } from './routes/sources.$sourceId'
import { Route as AssetsSourcesSourceIdRouteImport } from './routes/assets.sources.$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksIndexRoute = NotebooksIndexRouteImport.update({
  id: '/notebooks/',
  path: '/notebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksNotebookIdRoute = NotebooksNotebookIdRouteImport.update({
  id: '/notebooks/$notebookId',
  path: '/notebooks/$notebookId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSourcesSourceIdRoute = AssetsSourcesSourceIdRouteImport.update({
  id: '/assets/sources/$sourceId',
  path: '/assets/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/notebooks/': typeof NotebooksIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/assets/sources/$sourceId': typeof AssetsSourcesSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/notebooks': typeof NotebooksIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/assets/sources/$sourceId': typeof AssetsSourcesSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/notebooks/': typeof NotebooksIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/assets/sources/$sourceId': typeof AssetsSourcesSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notebooks/$notebookId'
    | '/sources/$sourceId'
    | '/notebooks/'
    | '/sources/'
    | '/assets/sources/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notebooks/$notebookId'
    | '/sources/$sourceId'
    | '/notebooks'
    | '/sources'
    | '/assets/sources/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/notebooks/$notebookId'
    | '/sources/$sourceId'
    | '/notebooks/'
    | '/sources/'
    | '/assets/sources/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotebooksNotebookIdRoute: typeof NotebooksNotebookIdRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  NotebooksIndexRoute: typeof NotebooksIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  AssetsSourcesSourceIdRoute: typeof AssetsSourcesSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/': {
      id: '/notebooks/'
      path: '/notebooks'
      fullPath: '/notebooks/'
      preLoaderRoute: typeof NotebooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/$notebookId': {
      id: '/notebooks/$notebookId'
      path: '/notebooks/$notebookId'
      fullPath: '/notebooks/$notebookId'
      preLoaderRoute: typeof NotebooksNotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/sources/$sourceId': {
      id: '/assets/sources/$sourceId'
      path: '/assets/sources/$sourceId'
      fullPath: '/assets/sources/$sourceId'
      preLoaderRoute: typeof AssetsSourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotebooksNotebookIdRoute: NotebooksNotebookIdRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  NotebooksIndexRoute: NotebooksIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  AssetsSourcesSourceIdRoute: AssetsSourcesSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
