/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotebooksRouteImport } from './routes/notebooks'
import { Route as SourcesSourceIdRouteImport } from './routes/sources.$sourceId'
import { Route as AssetsSourcesSourceIdRouteImport } from './routes/assets.sources.$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksRoute = NotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSourcesSourceIdRoute = AssetsSourcesSourceIdRouteImport.update({
  id: '/assets/sources/$sourceId',
  path: '/assets/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notebooks': typeof NotebooksRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/assets/sources/$sourceId': typeof AssetsSourcesSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notebooks': typeof NotebooksRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/assets/sources/$sourceId': typeof AssetsSourcesSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notebooks': typeof NotebooksRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/assets/sources/$sourceId': typeof AssetsSourcesSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/notebooks' | '/sources/$sourceId' | '/assets/sources/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notebooks' | '/sources/$sourceId' | '/assets/sources/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/notebooks'
    | '/sources/$sourceId'
    | '/assets/sources/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotebooksRoute: typeof NotebooksRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  AssetsSourcesSourceIdRoute: typeof AssetsSourcesSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks': {
      id: '/notebooks'
      path: '/notebooks'
      fullPath: '/notebooks'
      preLoaderRoute: typeof NotebooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/sources/$sourceId': {
      id: '/assets/sources/$sourceId'
      path: '/assets/sources/$sourceId'
      fullPath: '/assets/sources/$sourceId'
      preLoaderRoute: typeof AssetsSourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotebooksRoute: NotebooksRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  AssetsSourcesSourceIdRoute: AssetsSourcesSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
